#!/bin/bash

# Copy c-to-elf 
cp ../../docker-build/src/driver/c-to-elf-minio . 
mkdir -p usr
mkdir -p usr/include
mkdir -p usr/include/x86_64-linux-gnu
mkdir -p usr/include/x86_64-linux-gnu/bits
mkdir -p usr/include/x86_64-linux-gnu/gnu
mkdir -p usr/include/x86_64-linux-gnu/sys
mkdir -p usr/include/x86_64-linux-gnu/bits/types

# Copy system headers
cp  /usr/include/math.h     usr/include/math.h
cp  /usr/include/x86_64-linux-gnu/bits/libc-header-start.h     usr/include/x86_64-linux-gnu/bits/libc-header-start.h
cp  /usr/include/features.h     usr/include/features.h
cp  /usr/include/features-time64.h     usr/include/features-time64.h
cp  /usr/include/x86_64-linux-gnu/bits/wordsize.h     usr/include/x86_64-linux-gnu/bits/wordsize.h
cp  /usr/include/x86_64-linux-gnu/bits/timesize.h     usr/include/x86_64-linux-gnu/bits/timesize.h
cp  /usr/include/stdc-predef.h     usr/include/stdc-predef.h
cp  /usr/include/x86_64-linux-gnu/sys/cdefs.h     usr/include/x86_64-linux-gnu/sys/cdefs.h
cp  /usr/include/x86_64-linux-gnu/bits/long-double.h     usr/include/x86_64-linux-gnu/bits/long-double.h
cp  /usr/include/x86_64-linux-gnu/gnu/stubs.h     usr/include/x86_64-linux-gnu/gnu/stubs.h
cp  /usr/include/x86_64-linux-gnu/gnu/stubs-64.h     usr/include/x86_64-linux-gnu/gnu/stubs-64.h
cp  /usr/include/x86_64-linux-gnu/bits/types.h      usr/include/x86_64-linux-gnu/bits/types.h
cp  /usr/include/x86_64-linux-gnu/bits/typesizes.h     usr/include/x86_64-linux-gnu/bits/typesizes.h
cp  /usr/include/x86_64-linux-gnu/bits/time64.h     usr/include/x86_64-linux-gnu/bits/time64.h
cp  /usr/include/x86_64-linux-gnu/bits/math-vector.h     usr/include/x86_64-linux-gnu/bits/math-vector.h
cp  /usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h     usr/include/x86_64-linux-gnu/bits/libm-simd-decl-stubs.h
cp  /usr/include/x86_64-linux-gnu/bits/floatn.h     usr/include/x86_64-linux-gnu/bits/floatn.h
cp  /usr/include/x86_64-linux-gnu/bits/floatn-common.h     usr/include/x86_64-linux-gnu/bits/floatn-common.h
cp  /usr/include/x86_64-linux-gnu/bits/flt-eval-method.h     usr/include/x86_64-linux-gnu/bits/flt-eval-method.h
cp  /usr/include/x86_64-linux-gnu/bits/fp-logb.h     usr/include/x86_64-linux-gnu/bits/fp-logb.h
cp  /usr/include/x86_64-linux-gnu/bits/fp-fast.h     usr/include/x86_64-linux-gnu/bits/fp-fast.h
cp  /usr/include/x86_64-linux-gnu/bits/mathcalls-helper-functions.h     usr/include/x86_64-linux-gnu/bits/mathcalls-helper-functions.h
cp  /usr/include/x86_64-linux-gnu/bits/mathcalls.h     usr/include/x86_64-linux-gnu/bits/mathcalls.h
cp  /usr/include/string.h     usr/include/string.h
cp  /usr/include/x86_64-linux-gnu/bits/types/locale_t.h     usr/include/x86_64-linux-gnu/bits/types/locale_t.h
cp  /usr/include/x86_64-linux-gnu/bits/types/__locale_t.h     usr/include/x86_64-linux-gnu/bits/types/__locale_t.h
cp  /usr/include/strings.h     usr/include/strings.h
cp  /usr/include/assert.h     usr/include/assert.h
cp  /usr/include/alloca.h     usr/include/alloca.h
cp  /usr/include/stdlib.h     usr/include/stdlib.h
cp  /usr/include/x86_64-linux-gnu/bits/waitflags.h     usr/include/x86_64-linux-gnu/bits/waitflags.h
cp  /usr/include/x86_64-linux-gnu/bits/waitstatus.h     usr/include/x86_64-linux-gnu/bits/waitstatus.h
cp  /usr/include/x86_64-linux-gnu/sys/types.h     usr/include/x86_64-linux-gnu/sys/types.h
cp  /usr/include/x86_64-linux-gnu/bits/types/clock_t.h     usr/include/x86_64-linux-gnu/bits/types/clock_t.h
cp  /usr/include/x86_64-linux-gnu/bits/types/clockid_t.h     usr/include/x86_64-linux-gnu/bits/types/clockid_t.h
cp  /usr/include/x86_64-linux-gnu/bits/types/time_t.h     usr/include/x86_64-linux-gnu/bits/types/time_t.h
cp  /usr/include/x86_64-linux-gnu/bits/types/timer_t.h     usr/include/x86_64-linux-gnu/bits/types/timer_t.h
cp  /usr/include/x86_64-linux-gnu/bits/stdint-intn.h     usr/include/x86_64-linux-gnu/bits/stdint-intn.h
cp  /usr/include/x86_64-linux-gnu/bits/stdlib-bsearch.h     usr/include/x86_64-linux-gnu/bits/stdlib-bsearch.h
cp  /usr/include/endian.h     usr/include/endian.h
cp  /usr/include/x86_64-linux-gnu/bits/endian.h     usr/include/x86_64-linux-gnu/bits/endian.h
cp  /usr/include/x86_64-linux-gnu/bits/endianness.h     usr/include/x86_64-linux-gnu/bits/endianness.h
cp  /usr/include/x86_64-linux-gnu/bits/byteswap.h     usr/include/x86_64-linux-gnu/bits/byteswap.h
cp  /usr/include/x86_64-linux-gnu/bits/uintn-identity.h     usr/include/x86_64-linux-gnu/bits/uintn-identity.h
cp  /usr/include/x86_64-linux-gnu/sys/select.h     usr/include/x86_64-linux-gnu/sys/select.h
cp  /usr/include/x86_64-linux-gnu/bits/select.h     usr/include/x86_64-linux-gnu/bits/select.h
cp  /usr/include/x86_64-linux-gnu/bits/types/sigset_t.h     usr/include/x86_64-linux-gnu/bits/types/sigset_t.h
cp  /usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h     usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h
cp  /usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h     usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h
cp  /usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h     usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h
cp  /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h     usr/include/x86_64-linux-gnu/bits/pthreadtypes.h
cp  /usr/include/x86_64-linux-gnu/bits/thread-shared-types.h     usr/include/x86_64-linux-gnu/bits/thread-shared-types.h
cp  /usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h     usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h
cp  /usr/include/x86_64-linux-gnu/bits/atomic_wide_counter.h     usr/include/x86_64-linux-gnu/bits/atomic_wide_counter.h
cp  /usr/include/x86_64-linux-gnu/bits/struct_mutex.h     usr/include/x86_64-linux-gnu/bits/struct_mutex.h
cp  /usr/include/x86_64-linux-gnu/bits/struct_rwlock.h     usr/include/x86_64-linux-gnu/bits/struct_rwlock.h
cp  /usr/include/x86_64-linux-gnu/bits/stdlib-float.h     usr/include/x86_64-linux-gnu/bits/stdlib-float.h
cp  /usr/include/stdint.h     usr/include/stdint.h
cp  /usr/include/x86_64-linux-gnu/bits/wchar.h     usr/include/x86_64-linux-gnu/bits/wchar.h
cp  /usr/include/x86_64-linux-gnu/bits/stdint-uintn.h     usr/include/x86_64-linux-gnu/bits/stdint-uintn.h
cp  /usr/include/setjmp.h     usr/include/setjmp.h
cp  /usr/include/x86_64-linux-gnu/bits/setjmp.h     usr/include/x86_64-linux-gnu/bits/setjmp.h
cp  /usr/include/x86_64-linux-gnu/bits/types/struct___jmp_buf_tag.h     usr/include/x86_64-linux-gnu/bits/types/struct___jmp_buf_tag.h

# copy clang headers
mkdir -p clang-include 

cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/immintrin.h     clang-include/immintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/x86gprintrin.h     clang-include/x86gprintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/usermsrintrin.h     clang-include/usermsrintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/hresetintrin.h     clang-include/hresetintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/uintrintrin.h     clang-include/uintrintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/crc32intrin.h     clang-include/crc32intrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/prfchiintrin.h     clang-include/prfchiintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/raointintrin.h     clang-include/raointintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/mmintrin.h     clang-include/mmintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/xmmintrin.h     clang-include/xmmintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/mm_malloc.h     clang-include/mm_malloc.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/stdarg.h     clang-include/stdarg.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__stdarg_va_arg.h     clang-include/__stdarg_va_arg.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__stdarg___va_copy.h     clang-include/__stdarg___va_copy.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__stdarg_va_copy.h     clang-include/__stdarg_va_copy.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__stdarg_va_list.h     clang-include/__stdarg_va_list.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__stdarg___gnuc_va_list.h     clang-include/__stdarg___gnuc_va_list.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/stddef.h     clang-include/stddef.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__stddef_max_align_t.h     clang-include/__stddef_max_align_t.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__stddef_ptrdiff_t.h     clang-include/__stddef_ptrdiff_t.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__stddef_size_t.h     clang-include/__stddef_size_t.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__stddef_rsize_t.h     clang-include/__stddef_rsize_t.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__stddef_wchar_t.h     clang-include/__stddef_wchar_t.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__stddef_null.h     clang-include/__stddef_null.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__stddef_nullptr_t.h     clang-include/__stddef_nullptr_t.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__stddef_unreachable.h     clang-include/__stddef_unreachable.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__stddef_max_align_t.h     clang-include/__stddef_max_align_t.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__stddef_offsetof.h     clang-include/__stddef_offsetof.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__stddef_wint_t.h     clang-include/__stddef_wint_t.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/emmintrin.h     clang-include/emmintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/pmmintrin.h     clang-include/pmmintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/tmmintrin.h     clang-include/tmmintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/smmintrin.h     clang-include/smmintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/popcntintrin.h     clang-include/popcntintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/wmmintrin.h     clang-include/wmmintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__wmmintrin_aes.h     clang-include/__wmmintrin_aes.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/__wmmintrin_pclmul.h     clang-include/__wmmintrin_pclmul.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/clflushoptintrin.h     clang-include/clflushoptintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/clwbintrin.h     clang-include/clwbintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avxintrin.h     clang-include/avxintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx2intrin.h     clang-include/avx2intrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/f16cintrin.h     clang-include/f16cintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/bmiintrin.h     clang-include/bmiintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/bmi2intrin.h     clang-include/bmi2intrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/lzcntintrin.h     clang-include/lzcntintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/fmaintrin.h     clang-include/fmaintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512fintrin.h     clang-include/avx512fintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vlintrin.h     clang-include/avx512vlintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512bwintrin.h     clang-include/avx512bwintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512bitalgintrin.h     clang-include/avx512bitalgintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512cdintrin.h     clang-include/avx512cdintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vpopcntdqintrin.h     clang-include/avx512vpopcntdqintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vpopcntdqvlintrin.h     clang-include/avx512vpopcntdqvlintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vnniintrin.h     clang-include/avx512vnniintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vlvnniintrin.h     clang-include/avx512vlvnniintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avxvnniintrin.h     clang-include/avxvnniintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512dqintrin.h     clang-include/avx512dqintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vlbitalgintrin.h     clang-include/avx512vlbitalgintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vlbwintrin.h     clang-include/avx512vlbwintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vlcdintrin.h     clang-include/avx512vlcdintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vldqintrin.h     clang-include/avx512vldqintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512erintrin.h     clang-include/avx512erintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512ifmaintrin.h     clang-include/avx512ifmaintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512ifmavlintrin.h     clang-include/avx512ifmavlintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avxifmaintrin.h     clang-include/avxifmaintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vbmiintrin.h     clang-include/avx512vbmiintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vbmivlintrin.h     clang-include/avx512vbmivlintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vbmi2intrin.h     clang-include/avx512vbmi2intrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vlvbmi2intrin.h     clang-include/avx512vlvbmi2intrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512pfintrin.h     clang-include/avx512pfintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512fp16intrin.h     clang-include/avx512fp16intrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vlfp16intrin.h     clang-include/avx512vlfp16intrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512bf16intrin.h     clang-include/avx512bf16intrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vlbf16intrin.h     clang-include/avx512vlbf16intrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/pkuintrin.h     clang-include/pkuintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/vpclmulqdqintrin.h     clang-include/vpclmulqdqintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/vaesintrin.h     clang-include/vaesintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/gfniintrin.h     clang-include/gfniintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avxvnniint8intrin.h     clang-include/avxvnniint8intrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avxneconvertintrin.h     clang-include/avxneconvertintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/sha512intrin.h     clang-include/sha512intrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/sm3intrin.h     clang-include/sm3intrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/sm4intrin.h     clang-include/sm4intrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avxvnniint16intrin.h     clang-include/avxvnniint16intrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/amxcomplexintrin.h     clang-include/amxcomplexintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/rtmintrin.h     clang-include/rtmintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/xtestintrin.h     clang-include/xtestintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/shaintrin.h     clang-include/shaintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/fxsrintrin.h     clang-include/fxsrintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/xsaveintrin.h     clang-include/xsaveintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/xsaveoptintrin.h     clang-include/xsaveoptintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/xsavecintrin.h     clang-include/xsavecintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/xsavesintrin.h     clang-include/xsavesintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/cetintrin.h     clang-include/cetintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/adxintrin.h     clang-include/adxintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/rdseedintrin.h     clang-include/rdseedintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/wbnoinvdintrin.h     clang-include/wbnoinvdintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/cldemoteintrin.h     clang-include/cldemoteintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/waitpkgintrin.h     clang-include/waitpkgintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/movdirintrin.h     clang-include/movdirintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/pconfigintrin.h     clang-include/pconfigintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/sgxintrin.h     clang-include/sgxintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/ptwriteintrin.h     clang-include/ptwriteintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/invpcidintrin.h     clang-include/invpcidintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/amxfp16intrin.h     clang-include/amxfp16intrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/cmpccxaddintrin.h     clang-include/cmpccxaddintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/keylockerintrin.h     clang-include/keylockerintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/amxintrin.h     clang-include/amxintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vp2intersectintrin.h     clang-include/avx512vp2intersectintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/avx512vlvp2intersectintrin.h     clang-include/avx512vlvp2intersectintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/enqcmdintrin.h     clang-include/enqcmdintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/serializeintrin.h     clang-include/serializeintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/tsxldtrkintrin.h     clang-include/tsxldtrkintrin.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/stdint.h     clang-include/stdint.h
cp  ~/bootstrap/build/llvm-project/llvm/lib/clang/18/include/stdbool.h     clang-include/stdbool.h
